# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Updated version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast  # Checks Python syntax
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict  # Added to catch merge conflicts
    -   id: debug-statements  # Catches forgotten debugger statements

-   repo: https://github.com/psf/black
    rev: 23.7.0  # Updated version
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Updated version
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-typing-imports==1.15.0',
            'flake8-bugbear>=23.7.10',
            'flake8-docstrings>=1.7.0',
            'flake8-comprehensions>=3.14.0'
        ]
        args:
            - "--max-line-length=88"  # Match black's line length
            - "--extend-ignore=E203,W503,D100,D103,D107,D102,D104,D101,D106"
            - "--max-complexity=10"  # Limits function complexity

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]  # Makes isort compatible with black